### ISSUE TITLE
React Native Usage

### ISSUE THREAD

**Issue by stenmuchow** [TPAStream/stream-connect-js-sdk#28]
How can we use this package in RN? There is no DOM and hence no selector hook for the `el` key in the setup

**Comment by fuhrysteve** [comment]
Hi Sten!

Looks like we've exchanged emails. If you direct further issues to myself directly or through support@tpastream.com we'll be much more responsive there!

Thanks,

Steve

**Comment by stenmuchow** [comment]
Will do thanks! Writing it right now… 
Sten
